// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Vite only exposes env vars prefixed with `VITE_`, but Lovable Cloud may provide
// backend/public keys under non-VITE names depending on the runtime.
// We support both to avoid blank-screen crashes.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ??
  import.meta.env.SUPABASE_URL ??
  '';

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.SUPABASE_ANON_KEY ??
  '';

// Provide a dummy client when credentials are missing to prevent blank-screen crash.
// Any Supabase calls will simply fail gracefully.
function buildClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      '[Supabase] Missing credentials – running in offline / demo mode. ' +
        'VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be set.'
    );
    // Return a stub client that won't crash but won't work either
    return createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key',
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = buildClient();
