// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Pick the first non-empty env var.
 * Vite replaces import.meta.env at build time, but values can still end up as "".
 */
function pickEnv(...keys: string[]): string {
  for (const key of keys) {
    const value = (import.meta as unknown as { env: Record<string, string> }).env?.[key];
    if (typeof value === "string" && value.trim().length > 0) return value;
  }
  return "";
}

// Lovable Cloud provides VITE_* vars; we keep fallbacks for other runtimes.
const SUPABASE_URL = pickEnv("VITE_SUPABASE_URL", "SUPABASE_URL");
const SUPABASE_KEY = pickEnv(
  // Most common in Lovable Cloud
  "VITE_SUPABASE_PUBLISHABLE_KEY",
  "VITE_SUPABASE_ANON_KEY",
  // Non-vite fallbacks
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_ANON_KEY"
);

function buildClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    // Do NOT point to a fake URL (it causes noisy "Failed to fetch" errors).
    // Instead, provide a client whose requests fail fast with a clear message.
    const offlineFetch: typeof fetch = async () => {
      throw new Error(
        "Backend credentials are missing. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) are configured."
      );
    };

    return createClient<Database>("https://invalid.local", "invalid-key", {
      global: { fetch: offlineFetch },
      auth: { persistSession: false, autoRefreshToken: false },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = buildClient();

